#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Configure Apache Cassandra after the ensemble has started.
#

set -x
set -e

SELF_HOST=`/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

config_file=/etc/cassandra/conf/storage-conf.xml

seeds=""

for server in "$@"; do
  seeds="${seeds}<Seed>${server}</Seed>"
done

#TODO set replication
sed -i -e "s|<Seed>127.0.0.1</Seed>|$seeds|" $config_file
sed -i -e "s|<ListenAddress>localhost</ListenAddress>|<ListenAddress>$SELF_HOST</ListenAddress>|" $config_file
sed -i -e "s|<ThriftAddress>localhost</ThriftAddress>|<ThriftAddress>$SELF_HOST</ThriftAddress>|" $config_file

# Now that it's configured, start Cassandra
nohup /etc/rc.local &